"""Article 26 — Obligations of deployers of high-risk AI systems.

Note: most projects scanned by this tool are the DEPLOYER of a high-risk AI
system (they integrate a third-party model/API into their own product),
not the provider that built the underlying model. Art. 9/11/12/14/17 above
are framed mostly as provider duties; this analyzer tracks the distinct
deployer-side obligations of Art. 26 that are not already covered elsewhere:
assigning competent human oversight staff (26(2)), using the system per the
provider's instructions (26(1)), monitoring and reporting incidents (26(5)),
the deployer's own log-retention duty (26(6)), and informing individuals
subject to a high-risk decision (26(11)).
"""

from compliance_agent.analyzer.articles.base import (
    ArticleAnalyzer,
    ProjectProbe,
    Requirement,
    evidence,
    is_high_risk,
)
from compliance_agent.models.findings import ScanResult, Severity


class Art26Analyzer(ArticleAnalyzer):
    article_number = 26
    article_title = "Obligations of deployers of high-risk AI systems"

    def applies(self, scan_result: ScanResult) -> bool:
        return is_high_risk(scan_result)

    def requirements(self, scan_result: ScanResult, probe: ProjectProbe) -> list[Requirement]:
        return [
            Requirement(
                name="Deployer must use the system per the provider's instructions",
                status=evidence(
                    mechanism=False,
                    mention=probe.docs_mention(
                        "instructions of use", "operated in accordance with"
                    ),
                ),
                severity=Severity.WARNING,
                details=(
                    "Deployers must use high-risk AI systems in accordance with "
                    "the accompanying instructions of use (Art. 26(1))."
                ),
                suggestion=(
                    "Record that the provider's instructions of use are followed "
                    "operationally, not just received"
                ),
            ),
            Requirement(
                name="Human oversight must be assigned to competent, trained staff",
                status=evidence(
                    mechanism=False,
                    mention=probe.docs_mention(
                        "trained personnel", "trained staff", "human oversight training"
                    ),
                ),
                severity=Severity.HIGH,
                details=(
                    "Deployers must assign human oversight to natural persons who "
                    "have the necessary competence, training, and authority "
                    "(Art. 26(2)). This is distinct from Art. 14's design-level "
                    "oversight mechanism — it is the deployer's staffing duty."
                ),
                suggestion="Document who is assigned oversight duties and their training",
            ),
            Requirement(
                name="Deployer must monitor operation and report serious incidents",
                status=evidence(
                    mechanism=probe.code_mentions(
                        "report_incident", "incident_report", "serious_incident"
                    ),
                    mention=probe.docs_mention(
                        "serious incident", "incident reporting", "notify the provider"
                    ),
                ),
                severity=Severity.HIGH,
                details=(
                    "Deployers must monitor the system's operation and inform the "
                    "provider and market surveillance authority of risks or "
                    "serious incidents (Art. 26(5))."
                ),
                suggestion="Add an incident-reporting procedure and escalation path",
            ),
            Requirement(
                name="Deployer log retention (at least 6 months) required",
                status=evidence(
                    mechanism=probe.code_mentions(
                        "retention_months", "retention_until", "cleanup_expired", "log_retention"
                    ),
                    mention=probe.docs_mention("6 months", "six months", "retention period"),
                ),
                severity=Severity.HIGH,
                details=(
                    "Deployers must keep the logs automatically generated by the "
                    "AI system for at least 6 months, unless other law requires "
                    "otherwise (Art. 26(6))."
                ),
                suggestion=(
                    "Configure log retention with templates/art12/event_logging.py "
                    "(AILogger, cleanup_expired) and schedule the cleanup job"
                ),
            ),
            Requirement(
                name="Individuals subject to a high-risk AI decision must be informed",
                status=evidence(
                    mechanism=probe.code_mentions(
                        "automated_decision_notice",
                        "subject_to_automated_decision",
                        "right_to_explanation",
                        "decisionnotice",
                        "notify_subject",
                    ),
                    mention=probe.docs_mention(
                        "subject to an automated decision", "right to an explanation"
                    ),
                ),
                severity=Severity.HIGH,
                details=(
                    "Deployers must inform natural persons that they are subject "
                    "to the use of a high-risk AI system when it makes or assists "
                    "a decision about them (Art. 26(11))."
                ),
                suggestion=(
                    "Notify affected individuals and provide an explanation path "
                    "for decisions made about them"
                ),
            ),
        ]
