"""Article 50 — Transparency obligations for AI interacting with users."""

from compliance_agent.analyzer.articles.base import (
    ArticleAnalyzer,
    ProjectProbe,
    Requirement,
    evidence,
    has_ai,
    has_user_interaction,
)
from compliance_agent.models.findings import ScanResult, Severity


class Art50Analyzer(ArticleAnalyzer):
    article_number = 50
    article_title = "Transparency obligations (user-facing AI)"

    def applies(self, scan_result: ScanResult) -> bool:
        return has_ai(scan_result) and has_user_interaction(scan_result)

    def not_applicable_reason(self, scan_result: ScanResult) -> str:
        return "no user-facing AI interaction detected"

    def requirements(self, scan_result: ScanResult, probe: ProjectProbe) -> list[Requirement]:
        # "Met" requires an actual disclosure mechanism in code. Prose in a
        # README that merely mentions AI disclosure (or says it is missing) is
        # not evidence of an implemented control, so docs are not consulted here.
        has_disclosure = probe.code_mentions(
            "ai-disclosure",
            "transparency_notice",
            "x-ai-disclosure",
            "ai_transparency",
            "ai_disclosure",
            "generated by ai",
            "you are interacting with an ai",
            "this is an ai",
        )
        return [
            Requirement(
                name="AI interaction disclosure required",
                status=evidence(mechanism=has_disclosure),
                severity=Severity.HIGH,
                details=(
                    "Users appear to interact with AI output but no disclosure "
                    "mechanism was found. They must be informed they are "
                    "interacting with an AI system."
                ),
                suggestion=(
                    "Add a clear AI disclosure notice (templates/art50/transparency_notice.py)"
                ),
            ),
        ]
