"""
EU AI Act Article 50(4) — Deepfake Disclosure
Requirement: Deployers of AI systems that generate or manipulate image, audio,
or video content resembling real persons, places, or events (deepfakes) must
disclose that the content has been artificially generated or manipulated.

Usage: Route all synthetic media through label_media() before publishing.
"""

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path

DISCLOSURE_TEXT = "This content has been artificially generated or manipulated (EU AI Act, Art. 50)."


class MediaKind(StrEnum):
    IMAGE = "image"
    AUDIO = "audio"
    VIDEO = "video"


@dataclass
class DeepfakeLabel:
    """Disclosure record accompanying a piece of synthetic media."""

    media_kind: MediaKind
    generator: str  # model or tool that produced the media
    subject_consent: bool  # whether depicted persons consented
    created_at: str = ""

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.now(UTC).isoformat(timespec="seconds")


def caption_for(label: DeepfakeLabel) -> str:
    """Human-visible caption to render next to the media element."""
    return f"⚠️ {DISCLOSURE_TEXT} Generated by: {label.generator}."


def sidecar_path(media_path: Path) -> Path:
    """Path of the machine-readable sidecar file for a media asset."""
    return media_path.with_suffix(media_path.suffix + ".ai-disclosure.json")


def label_media(media_path: Path, label: DeepfakeLabel) -> Path:
    """Write a machine-readable disclosure sidecar file next to the media.

    Publishing pipelines should refuse to ship synthetic media without a
    sidecar. Returns the sidecar path.
    """
    record = {
        "disclosure": DISCLOSURE_TEXT,
        "media_kind": label.media_kind.value,
        "generator": label.generator,
        "subject_consent": label.subject_consent,
        "created_at": label.created_at,
        "media_file": media_path.name,
    }
    path = sidecar_path(media_path)
    path.write_text(json.dumps(record, indent=2), encoding="utf-8")
    return path


def is_labeled(media_path: Path) -> bool:
    """Check whether a media asset carries its disclosure sidecar."""
    return sidecar_path(media_path).is_file()


def html_overlay(label: DeepfakeLabel) -> str:
    """HTML snippet overlaying the disclosure on embedded media."""
    return (
        '<figure class="ai-media">\n'
        "  <!-- your <img>/<video>/<audio> element here -->\n"
        f'  <figcaption class="ai-media-disclosure">{caption_for(label)}</figcaption>\n'
        "</figure>"
    )


if __name__ == "__main__":
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        media = Path(tmp) / "avatar.png"
        media.write_bytes(b"\x89PNG fake bytes")
        label = DeepfakeLabel(MediaKind.IMAGE, generator="stable-diffusion-3", subject_consent=True)
        sidecar = label_media(media, label)
        print(f"labeled: {is_labeled(media)} -> {sidecar.name}")
        print(caption_for(label))
