"""
EU AI Act Article 50 — Transparency Notice
Requirement: Users must be informed they are interacting with an AI system.

Usage: Import and use in your chat interface, API endpoints, or UI.

- CLI/terminal apps: decorate your entry function with @ai_transparency_notice.
- FastAPI/Starlette (any ASGI app): app.add_middleware(AITransparencyMiddleware)
  or wrap the app directly: app = AITransparencyMiddleware(app).
- Streamlit: call show_streamlit_notice() at the top of your script.
"""

from collections.abc import Callable
from functools import wraps

TRANSPARENCY_BANNER = """
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ℹ️  AI INTERACTION NOTICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
You are interacting with an AI system as defined by
the EU AI Act (Regulation 2024/1689), Article 50.
Responses are generated by artificial intelligence
and may not always be accurate.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

# Short one-line variant for space-constrained UIs.
TRANSPARENCY_SHORT = (
    "ℹ️ You are interacting with an AI system (EU AI Act, Art. 50). "
    "Responses may not always be accurate."
)


def ai_transparency_notice(func: Callable) -> Callable:
    """Decorator that displays the AI transparency notice before execution.

    Use on the entry point of terminal/CLI chat loops so the notice is shown
    once, before the first AI interaction.
    """

    @wraps(func)
    def wrapper(*args, **kwargs):
        print(TRANSPARENCY_BANNER)
        return func(*args, **kwargs)

    return wrapper


class AITransparencyMiddleware:
    """ASGI middleware that adds AI disclosure headers to all HTTP responses.

    Works with FastAPI, Starlette, and any ASGI framework:

        from fastapi import FastAPI
        app = FastAPI()
        app.add_middleware(AITransparencyMiddleware)
    """

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        async def send_wrapper(message):
            if message["type"] == "http.response.start":
                headers = list(message.get("headers", []))
                # Machine-readable disclosure headers (Art. 50(1) and 50(2)).
                headers.append((b"x-ai-disclosure", b"AI-generated-content"))
                headers.append((b"x-ai-system", b"article-50-compliant"))
                message = {**message, "headers": headers}
            await send(message)

        await self.app(scope, receive, send_wrapper)


def show_streamlit_notice() -> None:
    """Render the disclosure notice in a Streamlit app.

    Call once at the top of your Streamlit script, before any chat widgets.
    """
    import streamlit as st  # local import: only needed in Streamlit apps

    st.info(TRANSPARENCY_SHORT, icon="ℹ️")


if __name__ == "__main__":
    # Demo: shows the banner around a trivial interaction.
    @ai_transparency_notice
    def demo_chat() -> None:
        print("assistant> Hello! (this response is AI-generated)")

    demo_chat()
