"""
AI Disclosure Middleware — Flask and FastAPI
Supports EU AI Act Article 50: users must be able to tell they are receiving
AI-generated content. Adds disclosure headers to every response and exposes
a standard /ai-disclosure endpoint describing the system.

Usage: pick the block matching your framework; delete the other.
"""

# Shared disclosure payload served at /ai-disclosure and mirrored in headers.
DISCLOSURE_INFO = {
    "ai_system": True,
    "regulation": "EU AI Act (Regulation 2024/1689), Article 50",
    "notice": (
        "Content served by this API may be generated by an AI system "
        "and may not always be accurate."
    ),
}

DISCLOSURE_HEADERS = {
    "X-AI-Disclosure": "AI-generated-content",
    "X-AI-System": "article-50-compliant",
}


# --- FastAPI ------------------------------------------------------------------
# from fastapi import FastAPI
#
# app = FastAPI()
# install_fastapi_disclosure(app)


def install_fastapi_disclosure(app) -> None:
    """Attach disclosure headers + /ai-disclosure endpoint to a FastAPI app."""

    @app.middleware("http")
    async def add_disclosure_headers(request, call_next):
        response = await call_next(request)
        for name, value in DISCLOSURE_HEADERS.items():
            response.headers[name] = value
        return response

    @app.get("/ai-disclosure")
    async def ai_disclosure() -> dict:
        return DISCLOSURE_INFO


# --- Flask --------------------------------------------------------------------
# from flask import Flask
#
# app = Flask(__name__)
# install_flask_disclosure(app)


def install_flask_disclosure(app) -> None:
    """Attach disclosure headers + /ai-disclosure endpoint to a Flask app."""
    from flask import jsonify  # local import: only needed in Flask apps

    @app.after_request
    def add_disclosure_headers(response):
        for name, value in DISCLOSURE_HEADERS.items():
            response.headers[name] = value
        return response

    @app.get("/ai-disclosure")
    def ai_disclosure():
        return jsonify(DISCLOSURE_INFO)
